import { chromium, devices } from "playwright";
import { readFileSync } from "fs";
const pw = readFileSync("../data/.qa-password", "utf8").trim();
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices["iPhone 13"] });
const page = await ctx.newPage();
const login = await page.request.post("https://server.lukeevanson.com:4201/api/auth/login", { data: { username: "qa", password: pw } });
const sc = login.headers()["set-cookie"] || "";
const token = sc.match(/rj2_session=([^;]+)/)?.[1];
await ctx.addCookies([{ name: "rj2_session", value: token, url: "https://server.lukeevanson.com:4201" }]);
const t0 = Date.now();
await page.goto("https://server.lukeevanson.com:4201/browse", { waitUntil: "domcontentloaded" });
await page.waitForSelector(".quick .chip:not([disabled])", { timeout: 40000 }).catch(() => {});
console.log("BOOT_MS", Date.now() - t0);
const state = await page.evaluate(() => ({ boot: document.body.innerText.slice(0, 120) }));
console.log("STATE", JSON.stringify(state));
await page.screenshot({ path: "qa/shots/browse-ios-home2.png" });
await page.fill("header input", "wikipedia.org");
await page.click(".go");
await page.waitForTimeout(9000);
await page.screenshot({ path: "qa/shots/browse-ios-wiki2.png" });
const href = await page.evaluate(() => document.querySelector("a.back")?.getAttribute("href"));
console.log("BACK_HREF", href);
const errs = [];
page.on("pageerror", (e) => errs.push(e.message));
console.log("DONE");
await browser.close();
