import { chromium, devices } from "playwright";
import { readFileSync } from "fs";
const pw = readFileSync("../data/.qa-password", "utf8").trim();
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices["iPhone 13"] });
const page = await ctx.newPage();
await page.addInitScript(() => {
  window.__medlog = [];
  const op = HTMLMediaElement.prototype.pause;
  HTMLMediaElement.prototype.pause = function () { window.__medlog.push((this.dataset?.idx || "aud") + ":pause@" + Math.round((this.currentTime || 0) * 10) / 10); return op.call(this); };
  const oq = HTMLMediaElement.prototype.play;
  HTMLMediaElement.prototype.play = function () { window.__medlog.push((this.dataset?.idx || "aud") + ":play"); return oq.call(this); };
});
const login = await page.request.post("http://127.0.0.1:14224/api/auth/login", { data: { username: "qa", password: pw } });
const token = (login.headers()["set-cookie"] || "").match(/rj2_session=([^;]+)/)?.[1];
await ctx.addCookies([{ name: "rj2_session", value: token, url: "http://127.0.0.1:14224" }]);
const errs = [];
page.on("pageerror", (e) => errs.push(String(e).slice(0, 200)));
await page.goto("http://127.0.0.1:14224/jetstream", { waitUntil: "domcontentloaded" });
await page.waitForSelector(".scard", { timeout: 20000 });
await page.tap(".scard");
await page.waitForSelector(".feed .slide video", { timeout: 10000 });
await page.waitForTimeout(2500);
const p = await page.$(".slide-play");
if (p) await p.tap().catch(() => {});
await page.waitForTimeout(4000);
await page.evaluate(() => { const w = document.querySelector(".feed-scroll"); w.scrollTo({ top: w.clientHeight, behavior: "auto" }); });
await page.waitForTimeout(3500);
const log = await page.evaluate(() => window.__medlog);
console.log("MEDLOG", JSON.stringify(log));
const st = await page.evaluate(() => {
  const v0 = document.querySelector(".slide[data-idx='0'] video");
  const v1 = document.querySelector(".slide[data-idx='1'] video");
  return { p0: v0?.paused, t0: Math.round((v0?.currentTime ?? -1) * 10) / 10, p1: v1?.paused, t1: Math.round((v1?.currentTime ?? -1) * 10) / 10 };
});
console.log("STATE", JSON.stringify(st));
console.log("ERRS", JSON.stringify(errs));
await browser.close();
