import { chromium } from "playwright";
import { readFileSync } from "fs";
const PW = readFileSync("/home/luke/goattech/ramjet-rebuild/data/.qa-password", "utf8").trim();
const BASE = "http://127.0.0.1:14224";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
page.on("response", (r) => { if (r.status() >= 400) console.log("BAD:", r.status(), r.url().slice(0, 140)); });
await page.goto(BASE + "/login");
const inputs = await page.$$("input");
await inputs[0].fill("qa"); await inputs[1].fill(PW);
await page.click("button[type=submit], button");
await page.waitForURL(BASE + "/", { timeout: 8000 });
await page.goto(BASE + "/jetstream");
await page.waitForTimeout(500);
await page.fill("input", "lofi girl");
await page.keyboard.press("Enter");
await page.waitForSelector(".row, .result, .card", { timeout: 15000 });
await page.waitForTimeout(2500);
console.log("-- jetstream done --");
await page.goto(BASE + "/amp");
await page.fill("input", "fred again");
await page.keyboard.press("Enter");
await page.waitForSelector(".row", { timeout: 15000 });
await page.waitForTimeout(3000);
console.log("-- amp search done --");
await browser.close();
