import { chromium } from "playwright";
import { readFileSync } from "fs";
const pw = readFileSync("../data/.qa-password", "utf8").trim();
const T0 = Date.now();
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
await ctx.route("**/*googlevideo.com/**", (r) => r.abort());
const page = await ctx.newPage();
const login = await page.request.post("http://127.0.0.1:14224/api/auth/login", { data: { username: "qa", password: pw } });
const token = (login.headers()["set-cookie"] || "").match(/rj2_session=([^;]+)/)?.[1];
await ctx.addCookies([{ name: "rj2_session", value: token, url: "http://127.0.0.1:14224" }]);
await page.goto("http://127.0.0.1:14224/jetstream", { waitUntil: "domcontentloaded" });
await page.waitForSelector(".scard", { timeout: 60000 });
await page.waitForTimeout(3000);
await page.click(".scard");
await page.waitForSelector(".feed .slide video", { timeout: 10000 });
await page.evaluate(() => { const v = document.querySelector(".feed .slide video"); v.muted = true; v.play(); });
await page.waitForTimeout(5000);
const t1 = await page.evaluate(() => document.querySelector(".feed .slide video").currentTime);
console.log("watched", t1.toFixed(1), "s; closing feed");
await page.click(".feed-back");
await page.waitForTimeout(1500);
// PATH 2: pagehide beacon
await page.click(".scard");
await page.waitForSelector(".feed .slide video", { timeout: 10000 });
await page.evaluate(() => { const v = document.querySelector(".feed .slide video"); v.muted = true; v.play(); });
await page.waitForTimeout(5000);
const t2 = await page.evaluate(() => document.querySelector(".feed .slide video").currentTime);
console.log("watched", t2.toFixed(1), "s; killing page");
await page.close();
await new Promise((r) => setTimeout(r, 2000));
console.log("T0 =", T0);
await browser.close();
