import { chromium } from "playwright";
import { readFileSync } from "fs";
const PW = readFileSync("/home/luke/goattech/ramjet-rebuild/data/.qa-password", "utf8").trim();
const BASE = "http://127.0.0.1:14224";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
page.on("console", (m) => console.log("CONSOLE:", m.type(), m.text().slice(0, 250)));
page.on("pageerror", (e) => console.log("PAGEERROR:", String(e).slice(0, 400)));
await page.goto(BASE + "/login");
const inputs = await page.$$("input");
await inputs[0].fill("qa"); await inputs[1].fill(PW);
await page.click("button[type=submit], button");
await page.waitForURL(BASE + "/", { timeout: 8000 });
await page.goto(BASE + "/sage");
await page.evaluate(() => localStorage.removeItem("sage-conversation"));
await page.reload();
await page.waitForTimeout(600);
await page.fill(".composer textarea", "say hi with one bold word");
await page.click(".composer button");
await page.waitForTimeout(10000);
const html = await page.evaluate(() => document.querySelector(".list")?.innerHTML?.slice(0, 600));
console.log("LIST HTML:", html);
await browser.close();
