import { chromium } from "playwright";
import { readFileSync } from "fs";
const PW = readFileSync("/home/luke/goattech/ramjet-rebuild/data/.qa-password", "utf8").trim();
const BASE = "http://127.0.0.1:14224";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
page.on("pageerror", (e) => console.log("PAGEERROR:", String(e).slice(0, 400)));
await page.goto(BASE + "/login");
const inputs = await page.$$("input");
await inputs[0].fill("qa"); await inputs[1].fill(PW);
await page.click("button[type=submit], button");
await page.waitForURL(BASE + "/", { timeout: 8000 });
await page.goto(BASE + "/sage");
await page.evaluate(() => localStorage.removeItem("sage-conversation"));
await page.reload();
await page.waitForTimeout(800);
await page.fill(".composer textarea", "one short tip for sleep");
await page.click(".composer button");
await page.waitForSelector(".msg:not(.mine) .bubble", { timeout: 90000 });
await page.waitForTimeout(1500);
console.log("LIST HTML:", (await page.evaluate(() => document.querySelector(".list")?.innerHTML))?.slice(0, 900));
console.log("STORAGE:", (await page.evaluate(() => localStorage.getItem("sage-conversation")))?.slice(0, 300));
await page.screenshot({ path: "/tmp/qa-sage-dom2.png" });
await browser.close();
