import { chromium } from "playwright";
const BASE = "http://127.0.0.1:14224";
const b = await chromium.launch();
const pg = await (await b.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
const errs = [];
pg.on("pageerror", (e) => errs.push("pageerror: " + e.message));
pg.on("console", (m) => { if (m.type() === "error") errs.push("console: " + m.text()); });
await pg.goto(BASE + "/login", { waitUntil: "networkidle" });
await pg.fill("input:not([type=password])", "qa");
await pg.fill("input[type=password]", process.env.QAPASS);
await pg.click("button[type=submit]");
await pg.waitForURL("**/", { timeout: 8000 }).catch(() => {});
await pg.goto(BASE + "/sage", { waitUntil: "networkidle" });
await pg.fill(".composer textarea", "say hi");
await pg.click(".composer button");
await pg.waitForSelector(".msg:not(.mine) .bubble", { timeout: 30000 });
await pg.click(".chatsbtn");
await pg.waitForSelector(".sheet");
await pg.click(".newchat");
await pg.waitForTimeout(1200);
console.log("messages after newchat:", await pg.locator(".msg").count());
console.log("sheet still open:", await pg.locator(".sheet").count());
console.log("empty visible:", await pg.locator(".empty .big").count());
await pg.screenshot({ path: "/tmp/sc-debug.png" });
console.log("JS errors:", errs.length ? errs.join(" | ") : "none");
await b.close();
