import { chromium } from "playwright";
const BASE = "http://127.0.0.1:14224";
const b = await chromium.launch();
const pg = await (await b.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
await pg.goto(BASE + "/login", { waitUntil: "networkidle" });
await pg.fill("input:not([type=password])", "qa");
await pg.fill("input[type=password]", process.env.QAPASS);
await pg.click("button[type=submit]");
await pg.waitForURL("**/", { timeout: 8000 }).catch(() => {});
await pg.goto(BASE + "/sage", { waitUntil: "networkidle" });
await pg.evaluate(() => { localStorage.clear(); });
await pg.reload({ waitUntil: "networkidle" });
await pg.fill(".composer textarea", "say hi");
await pg.click(".composer button");
await pg.waitForSelector(".msg:not(.mine) .bubble", { timeout: 30000 });
console.log("before sheet:", await pg.locator(".msg").count());
await pg.click(".chatsbtn");
await pg.waitForSelector(".sheet");
await pg.click(".newchat");
await pg.waitForTimeout(1500);
console.log("after newchat .msg count:", await pg.locator(".msg").count());
const bubbles = await pg.locator(".msg .bubble").allTextContents();
console.log("bubbles:", JSON.stringify(bubbles).slice(0, 200));
console.log("localStorage:", await pg.evaluate(() => localStorage.getItem("sage-conversation")));
console.log("error el:", await pg.locator(".error").count(), await pg.locator(".error").textContent().catch(() => ""));
await b.close();
