import { chromium, devices } from "playwright";
import { readFileSync } from "fs";
const pw = readFileSync("../data/.qa-password", "utf8").trim();
const mobile = process.argv[2] === "iphone";
const tag = mobile ? "iphone" : "desktop";
const browser = await chromium.launch();
const ctx = await browser.newContext(mobile ? { ...devices["iPhone 13"] } : { viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
const login = await page.request.post("http://127.0.0.1:14224/api/auth/login", { data: { username: "qa", password: pw } });
const token = (login.headers()["set-cookie"] || "").match(/rj2_session=([^;]+)/)?.[1];
await ctx.addCookies([{ name: "rj2_session", value: token, url: "http://127.0.0.1:14224" }]);
await page.goto("http://127.0.0.1:14224/jetstream", { waitUntil: "domcontentloaded" });
await page.waitForSelector(".scard", { timeout: 60000 });
await page.waitForTimeout(1200);
const dims = await page.evaluate(() => {
  const c = document.querySelector(".scard");
  const r = c.getBoundingClientRect();
  const t = c.querySelector(".sthumb").getBoundingClientRect();
  return { cardW: Math.round(r.width), cardH: Math.round(r.height), thumbH: Math.round(t.height), visible: Math.floor(window.innerWidth / r.width) };
});
console.log("DIMS", JSON.stringify(dims));
await page.screenshot({ path: `qa/shots/shelf-${tag}.png` });
await browser.close();
