import { chromium } from "playwright";
import { readFileSync } from "fs";
const PW = readFileSync("/home/luke/goattech/ramjet-rebuild/data/.qa-password", "utf8").trim();
const BASE = "http://127.0.0.1:14224";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
await page.goto(BASE + "/login");
const inputs = await page.$$("input");
await inputs[0].fill("qa"); await inputs[1].fill(PW);
await page.click("button[type=submit], button");
await page.waitForURL(BASE + "/", { timeout: 8000 });
await page.goto(BASE + "/browse");
await page.waitForTimeout(1000);
await page.fill("form input", "en.wikipedia.org");
await page.keyboard.press("Enter");
await page.waitForTimeout(12000);
const title = await page.evaluate(() => { try { return document.querySelector("iframe")?.contentDocument?.title || "EMPTY"; } catch { return "xo"; } });
console.log("frame:", title);
await browser.close();
